// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoMvUhyUeToxGTDTS1LJPB9YSr3aF433w',
    appId: '1:1062388842320:web:0d75e92987740d660c3655',
    messagingSenderId: '1062388842320',
    projectId: 'flutterauthen-b9fe7',
    authDomain: 'flutterauthen-b9fe7.firebaseapp.com',
    storageBucket: 'flutterauthen-b9fe7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMa2Q3KAWlL8ZnN3ypGADqAiYbvvBtZGI',
    appId: '1:1062388842320:android:0821c68455062ea90c3655',
    messagingSenderId: '1062388842320',
    projectId: 'flutterauthen-b9fe7',
    storageBucket: 'flutterauthen-b9fe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyVeJ2x9ozkarh7rzM783w1PBtjtVyuEU',
    appId: '1:1062388842320:ios:8da941631b8e27d50c3655',
    messagingSenderId: '1062388842320',
    projectId: 'flutterauthen-b9fe7',
    storageBucket: 'flutterauthen-b9fe7.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyVeJ2x9ozkarh7rzM783w1PBtjtVyuEU',
    appId: '1:1062388842320:ios:011bbd5bc12b40a50c3655',
    messagingSenderId: '1062388842320',
    projectId: 'flutterauthen-b9fe7',
    storageBucket: 'flutterauthen-b9fe7.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
